{{- if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {{- if .Values.crds.keep }}
    "helm.sh/resource-policy": keep
    {{- end }}
    {{- with .Values.crds.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name:  externals.dev.okteto.com
  name: externals.dev.okteto.com
spec:
  group: dev.okteto.com
  names:
    kind: External
    listKind: ExternalList
    plural: externals
    singular: external
    shortNames:
    - er
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: External is the schema for the external resources which stores the needed information for each element
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            required:
              - name
              - endpoints
            properties:
              name:
                type: string
              icon:
                type: string
                default: default
                enum:
                - container
                - dashboard
                - database
                - default
                - function
                - graph
                - storage
                - launchdarkly
                - mongodb
                - gcp
                - aws
                - okteto
              notes:
                type: object
                required:
                - path
                - markdown
                properties:
                  path:
                    type: string
                  markdown:
                    type: string
              endpoints:
                type: array
                items:
                  type: object
                  required:
                  - name
                  - url
                  properties:
                    name:
                      type: string
                    url:
                      type: string
    served: true
    storage: true
{{- end }}
