{{- if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dynamicconfigs.admin.okteto.com
  labels:
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: dynamicconfigs.admin.okteto.com
  annotations:
    {{- if .Values.crds.keep }}
    "helm.sh/resource-policy": keep
    {{- end }}
    {{- with .Values.crds.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  group: admin.okteto.com
  scope: Namespaced
  names:
    kind: DynamicConfig
    listKind: DynamicConfigList
    plural: dynamicconfigs
    singular: dynamicconfig
    shortNames:
    - dynconf
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          oneOf:
            - properties:
              required:
                - secretRef
            - properties:
              required:
                - spec
          properties:
            secretRef:
              type: string
            spec:
              x-kubernetes-preserve-unknown-fields: true
              additionalProperties:
                type: string
              type: object
status:
  acceptedNames:
    kind: DynamicConfig
    listKind: DynamicConfigList
    plural: dynamicconfigs
    singular: dynamicconfig
  conditions: []
  storedVersions: []
{{- end }}