apiVersion: v1
kind: ConfigMap
metadata:
  name: okteto-support-bundle
  namespace: {{ .Release.Namespace }}
  labels:
    troubleshoot.sh/kind: support-bundle
    app.kubernetes.io/component: "diagnostics"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-support-bundle"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  support-bundle-spec: {{ include "okteto.diagnostics.supportBundleSpec" . | toYaml | nindent 4 -}}
