{{- if .Values.gc.enabled }}
apiVersion: {{ template "okteto.cronJob.apiVersion" . }}
kind: CronJob
metadata:
  name: "{{ include "okteto.fullname" . }}-gc"
  labels:
    app.kubernetes.io/component: "gc"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-gc"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  schedule: "{{ .Values.gc.schedule }}"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: "gc"
        app.kubernetes.io/part-of: "okteto"
    spec:
      activeDeadlineSeconds: {{ .Values.gc.timeoutInSeconds }}
      ttlSecondsAfterFinished: {{ .Values.globals.jobs.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            app.kubernetes.io/component: "gc"
            app.kubernetes.io/part-of: "okteto"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 12 }}
{{- end }}
{{- if .Values.gc.labels }}
{{ toYaml .Values.gc.labels | indent 12 }}
{{- end }}
{{- if or .Values.podAnnotations .Values.gc.annotations }}
          annotations:
  {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 12 }}
  {{- end }}
  {{- if .Values.gc.annotations }}
{{ toYaml .Values.gc.annotations | indent 12 }}
  {{- end }}
{{- end }}
        spec:
          affinity:
            nodeAffinity:
{{ include "okteto.oktetoAffinity" . | indent 14 }}
          serviceAccountName: {{ include "okteto.fullname" . }}
          {{- include "okteto.tolerations" (dict "globalsTolerations" .Values.globals.tolerations.okteto "poolTolerations" .Values.tolerations.oktetoPool ) | nindent 10 }}
          {{- include "okteto.nodeSelectors" (dict "poolTolerations" .Values.tolerations.oktetoPool "nodeSelectors" .Values.globals.nodeSelectors.okteto ) | nindent 10 }}
          volumes:
          - name: tls-certs
            secret:
              defaultMode: 420
              secretName: {{ include "okteto.ingress.tlsSecret" . }}
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
          containers:
            - name: gc
              image: {{ include "okteto.image.backend" . }}
              imagePullPolicy: {{ .Values.pullPolicy }}
              args: [ "gc" ]
              env:
                - name: OKTETO_INGRESS_INTERNAL_IP
                  value: "{{ include "okteto.ingressprivateip" . }}"
                - name: OKTETO_BUILDKIT_INTERNAL_IP
                  value: "{{ include "okteto.buildkitprivateip" . }}"
{{- if .Values.gc.extraEnv }}
{{ toYaml .Values.gc.extraEnv | indent 16 }}
{{- end }}
              envFrom:
                - configMapRef:
                    name: "{{ include "okteto.fullname" . }}"
                - secretRef:
                    name: {{ include "okteto.fullname" . }}
                - secretRef:
                    name: "{{ .Values.cloud.secret.name }}"
                    optional: true
              volumeMounts:
                - name: tls-certs
                  mountPath: /run/secrets/tls
                  readOnly: true
          priorityClassName: {{ .Values.gc.priorityClassName | default .Values.globals.priorityClassName }}
{{- end }}
