{{- if not .Values.cluster.endpoint }}
{{- $url := urlParse (include "okteto.clusterEndpoint" .) -}}
{{- $hostParts := mustRegexSplit ":" (get $url "host" ) -1 -}}
{{- $host := first $hostParts -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "okteto.fullname" . }}-cluster-endpoint
  labels:
    app.kubernetes.io/name: {{ include "okteto.fullname" . }}-cluster-endpoint
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/component: "cluster-endpoint"
  annotations:
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: "on"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ include "okteto.oktetoIngressClass" . }}
  tls:
  - hosts:
    - "{{ $host }}"
    secretName: {{ include "okteto.ingress.tlsSecret" . }}
  rules:
    - host: "{{ $host }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ include "okteto.fullname" . }}-cluster-endpoint
                port:
                  number: 443
{{- end }}
