{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "okteto.fullname" . }}-migration"
  labels:
    app.kubernetes.io/component: "migration"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-migration"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- with .Values.migration.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ttlSecondsAfterFinished: {{ .Values.globals.jobs.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-migration"
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "migration"
        app.kubernetes.io/part-of: "okteto"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
{{- if .Values.migration.labels }}
{{ toYaml .Values.migration.labels | indent 8 }}
{{- end }}
{{- if or .Values.podAnnotations .Values.migration.annotations }}
      annotations:
  {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
  {{- end }}
  {{- if .Values.migration.annotations }}
{{ toYaml .Values.migration.annotations | indent 8 }}
  {{- end }}
{{- end }}
    spec:
      affinity:
        nodeAffinity:
{{ include "okteto.oktetoAffinity" . | indent 10 }}
      restartPolicy: Never
      priorityClassName: {{ .Values.migration.priorityClassName | default .Values.globals.priorityClassName }}
      serviceAccountName: {{ include "okteto.fullname" . }}
      {{- include "okteto.tolerations" (dict "globalsTolerations" .Values.globals.tolerations.okteto "poolTolerations" .Values.tolerations.oktetoPool ) | nindent 6 }}
      {{- include "okteto.nodeSelectors" (dict "poolTolerations" .Values.tolerations.oktetoPool "nodeSelectors" .Values.globals.nodeSelectors.okteto ) | nindent 6 }}
      volumes:
        - name: tls-certs
          secret:
            defaultMode: 420
            secretName: {{ include "okteto.ingress.tlsSecret" . }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: api
          image: {{ include "okteto.image.backend" . }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          args: [ "migrate" ]
          envFrom:
          - configMapRef:
              name: "{{ include "okteto.fullname" . }}"
          - secretRef:
              name: {{ include "okteto.fullname" . }}
          - secretRef:
              name: "{{ .Values.cloud.secret.name }}"
              optional: true
          volumeMounts:
            - name: tls-certs
              mountPath: /run/secrets/tls
              readOnly: true
          resources:
{{ toYaml .Values.migration.resources | indent 12 }}
{{- end }}
