{{- $serviceName := include "okteto.fullname" . -}}
{{- $customAnnotations := (include "okteto.serviceaccountsannotations" . | fromJson) -}}
{{- $customLabels := (include "okteto.serviceaccountslabels" . | fromJson) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: okteto-cluster-admin
  labels:
    app: {{ $serviceName }}
    chart: "{{ .Chart.Name }}-{{ include "okteto.version" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- range $key, $value := $customLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- if $customAnnotations }}
  annotations:
    {{- range $key, $value := $customAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}

