{{- $serviceName := include "okteto.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: okteto-bot
  labels:
    app: {{ $serviceName }}
    chart: "{{ .Chart.Name }}-{{ include "okteto.version" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    dev.okteto.com: "true"
    dev.okteto.com/id: "okteto-bot"
    dev.okteto.com/external-id: "{{ .Values.oktetoBotUser }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    dev.okteto.com/super: "true"
    dev.okteto.com/token: "{{ include "okteto.botUserToken" . }}"
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
