{{- if .Values.registry.gc.enabled }}
{{- $name := include "okteto.fullNameCronJob" (dict "context" . "suffix" "registry-gc") }}
{{- $secret := include "okteto.registry.secret" . | trim | nindent 2 | fromYaml -}}
apiVersion: {{ template "okteto.cronJob.apiVersion" . }}
kind: CronJob
metadata:
  name: "{{ $name }}"
  labels:
    app.kubernetes.io/component: "registry-gc"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ $name }}"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  schedule: "{{ .Values.registry.gc.schedule }}"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: "registry-gc"
        app.kubernetes.io/part-of: "okteto"
    spec:
      activeDeadlineSeconds: {{ .Values.registry.gc.timeoutInSeconds }}
      ttlSecondsAfterFinished: {{ .Values.globals.jobs.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            app.kubernetes.io/component: "registry-gc"
            app.kubernetes.io/part-of: "okteto"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 12 }}
{{- end }}
{{- if .Values.registry.gc.labels }}
{{ toYaml .Values.registry.gc.labels | indent 12 }}
{{- end }}
{{- if or .Values.podAnnotations .Values.registry.gc.annotations }}
          annotations:
  {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 12 }}
  {{- end }}
  {{- if .Values.registry.gc.annotations }}
{{ toYaml .Values.registry.gc.annotations | indent 12 }}
  {{- end }}
{{- end }}
        spec:
          affinity:
            nodeAffinity:
{{ include "okteto.oktetoAffinity" . | indent 14 }}
          serviceAccountName: {{ include "okteto.fullname" . }}
          {{- include "okteto.tolerations" (dict "globalsTolerations" .Values.globals.tolerations.okteto "poolTolerations" .Values.tolerations.oktetoPool ) | nindent 10 }}
          {{- include "okteto.nodeSelectors" (dict "poolTolerations" .Values.tolerations.oktetoPool "nodeSelectors" .Values.globals.nodeSelectors.okteto ) | nindent 10 }}
          volumes:
          - name: tls-certs
            secret:
              defaultMode: 420
              secretName: {{ include "okteto.ingress.tlsSecret" . }}
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
          containers:
            - name: registry-gc
              image: {{ include "okteto.image.backend" . }}
              imagePullPolicy: {{ .Values.pullPolicy }}
              args: [ "registry-gc" ]
              envFrom:
                - configMapRef:
                    name: "{{ include "okteto.fullname" . }}"
                - secretRef:
                    name: {{ include "okteto.fullname" . }}
                - secretRef:
                    name: {{ $secret.name }}
                    optional: true
              volumeMounts:
                - name: tls-certs
                  mountPath: /run/secrets/tls
                  readOnly: true
{{- end }}
