{{- if eq (include "okteto.authToken.enabled" .) "true" }}
{{- $serviceName := include "okteto.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: okteto-admin
  labels:
    app: {{ $serviceName }}
    chart: "{{ .Chart.Name }}-{{ include "okteto.version" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    dev.okteto.com: "true"
    dev.okteto.com/token: "{{ include "okteto.authToken" . }}"
    dev.okteto.com/id: "okteto-admin"
    dev.okteto.com/external-id: "okteto-admin"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    dev.okteto.com/super: "true"
  annotations:
    "helm.sh/resource-policy": keep
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    dev.okteto.com/email: "welcome@okteto.com"
{{- end }}
