apiVersion: v1
kind: Service
metadata:
  name: "{{ include "okteto.webhook" . }}"
  labels:
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.webhook" . }}"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webhook.port }}
      name: webhook
      targetPort: https
  selector:
    app.kubernetes.io/name: "{{ include "okteto.webhook" . }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
