{{- if eq (include "okteto.defaultBackend.enabled" .) "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "okteto.defaultBackendName" . }}
  labels:
    app.kubernetes.io/component: default-backend
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: {{ include "okteto.defaultBackendName" . }}
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ include "okteto.tlsSecretsToReload" . }},{{ .Values.cloud.secret.name }}"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  replicas: {{ .Values.defaultBackend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "okteto.defaultBackendName" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "okteto.defaultBackendName" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: default-backend
        app.kubernetes.io/part-of: "okteto"
        {{- if .Values.podLabels }}
        {{ toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
        {{- if .Values.defaultBackend.labels }}
        {{ toYaml .Values.defaultBackend.labels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.defaultBackend.annotations }}
        {{ toYaml .Values.defaultBackend.annotations | nindent 8 }}
        {{- end }}
    spec:
      affinity:
        nodeAffinity:
          {{ include "okteto.oktetoAffinity" . | nindent 10 }}
        podAntiAffinity:
          {{- if .Values.affinity.required }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - {{ include "okteto.defaultBackendName" . }}
              topologyKey: kubernetes.io/hostname
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                      - {{ include "okteto.defaultBackendName" . }}
                topologyKey: kubernetes.io/hostname
          {{- end }}
      serviceAccountName: {{ include "okteto.fullname" . }}
      {{- include "okteto.tolerations" (dict "globalsTolerations" .Values.globals.tolerations.okteto "poolTolerations" .Values.tolerations.oktetoPool ) | nindent 6 }}
      {{- include "okteto.nodeSelectors" (dict "poolTolerations" .Values.tolerations.oktetoPool "nodeSelectors" .Values.globals.nodeSelectors.okteto ) | nindent 6 }}
      volumes:
        - name: tls-certs
          secret:
            defaultMode: 420
            secretName: {{ include "okteto.registry.tlsSecret" . }}
        {{- if eq "true" (include "okteto.privateca.enabled" .) }}
        - name: ca-pemstore
          secret:
            defaultMode: 420
            secretName: {{ include "okteto.privateca.secretname" . }}
        {{- end }}
      priorityClassName: {{ .Values.defaultBackend.priorityClassName | default .Values.globals.priorityClassName }}
      containers:
        - name: default-backend
          image: {{ include "okteto.image.defaultBackend" . }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          args: ["error-pages"]
          ports:
            - name: http
              containerPort: {{ .Values.defaultBackend.port }}
              protocol: TCP
          env:
            {{- if .Values.defaultBackend.extraEnvs }}
            {{- toYaml .Values.defaultBackend.extraEnvs | nindent 12 }}
            {{- end }}
          envFrom:
          - configMapRef:
              name: "{{ include "okteto.fullname" . }}"
          - secretRef:
              name: {{ include "okteto.fullname" . }}
          - secretRef:
              name: "{{ .Values.cloud.secret.name }}"
              optional: true
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.defaultBackend.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.defaultBackend.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.defaultBackend.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
{{- end }}
