{{- if .Values.insights.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ include "okteto.fullname" . }}-eventsexporter"
  labels:
    app.kubernetes.io/component: "eventsexporter"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-eventsexporter"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ .Values.cloud.secret.name }}"
spec:
  serviceName: "{{ include "okteto.fullname" . }}-eventsexporter"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-eventsexporter"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-eventsexporter"
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "eventsexporter"
        app.kubernetes.io/part-of: "okteto"
        {{- if .Values.podLabels }}
        {{ toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
        {{- if .Values.insights.eventsExporter.podLabels }}
        {{ toYaml .Values.insights.eventsExporter.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.insights.eventsExporter.podAnnotations }}
        {{ toYaml .Values.insights.eventsExporter.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 0
      affinity:
        nodeAffinity: {{ include "okteto.oktetoAffinity" . | nindent 10 }}
        podAntiAffinity:
          {{- if .Values.affinity.required }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - "{{ include "okteto.fullname" . }}-eventsexporter"
              topologyKey: kubernetes.io/hostname
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                      - "{{ include "okteto.fullname" . }}-eventsexporter"
                topologyKey: kubernetes.io/hostname
          {{- end }}
      serviceAccountName: {{ include "okteto.fullname" . }}
      {{- include "okteto.tolerations" (dict "globalsTolerations" .Values.globals.tolerations.okteto "poolTolerations" .Values.tolerations.oktetoPool ) | nindent 6 }}
      {{- include "okteto.nodeSelectors" (dict "poolTolerations" .Values.tolerations.oktetoPool "nodeSelectors" .Values.globals.nodeSelectors.okteto ) | nindent 6 }}
      priorityClassName: {{ .Values.insights.eventsExporter.priorityClassName | default .Values.globals.priorityClassName }}
      volumes:
        - name: tls-certs
          secret:
            defaultMode: 420
            secretName: {{ include "okteto.ingress.tlsSecret" . }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: watcher
          image: {{ include "okteto.image.backend" . }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          args: [ "eventsexporter" ]
          envFrom:
          - configMapRef:
              name: "{{ include "okteto.fullname" . }}"
          - secretRef:
              name: {{ include "okteto.fullname" . }}
          - secretRef:
              name: "{{ .Values.cloud.secret.name }}"
              optional: true
          volumeMounts:
            - name: tls-certs
              mountPath: /run/secrets/tls
              readOnly: true
          resources: {{ toYaml .Values.insights.eventsExporter.resources | nindent 12 }}
{{- end }}
