apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "helm-release-meta"
    app.kubernetes.io/part-of: "okteto"
  name: "okteto-helm-release-meta"
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $val := .Release }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
