{{- if .Values.installerChecker.enabled }}
{{- $name := include "okteto.fullNameCronJob" (dict "context" . "suffix" "installer-checker") }}
apiVersion: {{ template "okteto.cronJob.apiVersion" . }}
kind: CronJob
metadata:
  name: "{{ $name }}"
  labels:
    app.kubernetes.io/component: "installer-checker"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ $name }}"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.installerChecker.schedule }}"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: "installer-checker"
        app.kubernetes.io/part-of: "okteto"
    spec:
      ttlSecondsAfterFinished: {{ .Values.globals.jobs.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            app.kubernetes.io/component: "installer-checker"
            app.kubernetes.io/part-of: "okteto"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 12 }}
{{- end }}
{{- if .Values.podAnnotations }}
          annotations:
{{ toYaml .Values.podAnnotations | indent 12 }}
  {{- end }}
        spec:
          affinity:
            nodeAffinity:
{{ include "okteto.oktetoAffinity" . | indent 14 }}
          serviceAccountName: {{ include "okteto.fullname" . }}
          priorityClassName: {{ .Values.installerChecker.priorityClassName | default .Values.globals.priorityClassName }}
          {{- include "okteto.tolerations" (dict "globalsTolerations" .Values.globals.tolerations.okteto "poolTolerations" .Values.tolerations.oktetoPool ) | nindent 10 }}
          {{- include "okteto.nodeSelectors" (dict "poolTolerations" .Values.tolerations.oktetoPool "nodeSelectors" .Values.globals.nodeSelectors.okteto ) | nindent 10 }}
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
          containers:
            - name: installer-checker
              image: {{ include "okteto.image.backend" . }}
              imagePullPolicy: {{ .Values.pullPolicy }}
              args: [ "installer-checker" ]
              envFrom:
              - configMapRef:
                  name: "{{ include "okteto.fullname" . }}"
              - secretRef:
                  name: {{ include "okteto.fullname" . }}
              - secretRef:
                  name: "{{ .Values.cloud.secret.name }}"
                  optional: true

{{- end }}
