{{- if .Values.resourceManager.enabled }}
{{- $name := include "okteto.fullNameCronJob" (dict "context" . "suffix" "resourcemanager") }}
apiVersion: {{ template "okteto.cronJob.apiVersion" . }}
kind: CronJob
metadata:
  name: "{{ $name }}"
  labels:
    app.kubernetes.io/component: "resourcemanager"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ $name }}"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  schedule: "{{ .Values.resourceManager.schedule }}"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: "resourcemanager"
        app.kubernetes.io/part-of: "okteto"
    spec:
      ttlSecondsAfterFinished: {{ .Values.globals.jobs.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            app.kubernetes.io/component: "resourcemanager"
            app.kubernetes.io/part-of: "okteto"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 12 }}
{{- end }}
{{- if .Values.resourceManager.labels }}
{{ toYaml .Values.resourceManager.labels | indent 12 }}
{{- end }}
{{- if or .Values.podAnnotations .Values.resourceManager.annotations }}
          annotations:
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 12 }}
{{- end }}
{{- if .Values.resourceManager.annotations }}
{{ toYaml .Values.resourceManager.annotations | indent 12 }}
{{- end }}
{{- end }}
        spec:
          affinity:
            nodeAffinity:
{{ include "okteto.oktetoAffinity" . | indent 14 }}
          serviceAccountName: {{ include "okteto.fullname" . }}
          {{- include "okteto.tolerations" (dict "globalsTolerations" .Values.globals.tolerations.okteto "poolTolerations" .Values.tolerations.oktetoPool ) | nindent 10 }}
          {{- include "okteto.nodeSelectors" (dict "poolTolerations" .Values.tolerations.oktetoPool "nodeSelectors" .Values.globals.nodeSelectors.okteto ) | nindent 10 }}
          restartPolicy: Never
          priorityClassName: {{ .Values.resourceManager.priorityClassName | default .Values.globals.priorityClassName }}
          securityContext:
            runAsNonRoot: true
          containers:
            - name: compute
              image: "{{ include "okteto.image.backend" . }}"
              imagePullPolicy: {{ .Values.pullPolicy }}
              args: [ "resource-manager", "compute"]
              resources:
                {{ toYaml .Values.resourceManager.resources | nindent 16 }}
              envFrom:
                - configMapRef:
                    name: "{{ include "okteto.fullname" . }}"
{{- end }}
