{{- if .Values.unsupported.sleepingIngressClass.enabled -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.unsupported.sleepingIngressClass.name }}
spec:
  controller: dev.okteto.com/gc
{{- end -}}